---
# tasks file for ansible-nfs-client
- ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- ansible.builtin.import_tasks: config.yml
